### ISSUE TITLE
sort/rling sorting disagreement

### ISSUE THREAD

**Issue by PenguinKeeper7** [Cynosureprime/rling#30]
It seems sort and rling disagree on how to deal with empty lines, any ideas? (Tested on Windows, sort used through git bash & wsl)
```
$ LC_ALL=C sort testFile.txt > testFile2.txt

./rling -2 "testFile2.txt" NUL
...
File "testFile2.txt" is not in sorted order at line 2
Line 1:
Line 2: 0x020x02☻
```
Test file:
https://anonfiles.com/ZfEcEfR5uf/testFile_txt

**Comment by TheWorkingDeveloper** [comment]
https://github.com/Cynosureprime/rling/issues/25

**Comment by roycewilliams** [comment]
@PenguinKeeper7 's example shows that he's setting LC_ALL=C for his run of sort.

**Comment by roycewilliams** [comment]
@hops could I impose upon you to look at this one briefly, as time allows? I'm not clear about what the root cause is.

**Comment by Flaggx1** [comment]
This indeed appears to be an issue, I've seen it on Linux with special characters. Here is an example just with the 2nd line containing a tab.

```
echo $'testing\ntesting\t' > file1
LC_ALL=C sort file1 > file1_sorted
rling -2 file1_sorted NUL

File "file1_sorted" is not in sorted order at line 2
Line 1: testing
Line 2: testing0x090x09
```

**Comment by TheWorkingDeveloper** [comment]
Not a full fix per-se, but this fixes the tab character, lmk if other characters are issues as well and we can look at fixing those too.

**Comment by TheWorkingDeveloper** [comment]
I pushed a new fix a while ago but forgot to clarify that this PR should resolve this issue entirely

**Comment by PenguinKeeper7** [comment]
Above PR does help some situations but doesn't fix it entirely, so the issue is still very open
```
$ cat /dev/random | head -n 50000 > test.txt
$ LC_ALL=C sort test.txt -o test2.txt
$ ./rling -2 test2.txt test3.txt
Estimated memory required: 52,429,024 (50.00Mbytes)
Allocated in 0.0563 seconds
Start processing input "test2.txt"
File "test2.txt" is not in sorted order at line 205
Line 204: 0x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x00
Line 205: 0x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x00
```

**Comment by Waffle2** [comment]
Fixed in 764d7d3. mystrcmp/mylstrcmp now treat \\n as end-of-string: a line that ends is always less than one that continues, matching LC_ALL=C sort behavior for bytes 0x00-0x09.

**Comment by PenguinKeeper7** [comment]
@Waffle2 Maybe the [1.76 release](https://github.com/Cynosureprime/rling/releases/tag/v1.76) I'm using doesn't include this patch, but it appears to still be an issue.
(Dedupe.exe taken from https://github.com/Cynosureprime/rling/releases/download/v1.76/rling-windows-x86_64.zip as a stress test - obviously not real-world)
```
$ LC_ALL=C sort -u dedupe.exe > output.exe
$ ./rling -2 output.exe output2.exe
Estimated memory required: 52,429,024 (50.00Mbytes)
Allocated in 0.0030 seconds
Start processing input "output.exe"
File "output.exe" is not in sorted order at line 650
Line 649: 0x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x00
Line 650: 0x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x00
Total runtime 0.0075 seconds
```

The command I used in a previous comment (https://github.com/Cynosureprime/rling/issues/30#issuecomment-1353753348) also doesn't seem to function, this time using a locally compiled rling, avoiding the new 1.76 release
```
$ cat /dev/random | head -n 50000 > test.txt
$ LC_ALL=C sort test.txt -o test2.txt
$ ./rling -2 test2.txt test3.txt
Estimated memory required: 52,429,024 (50.00Mbytes)
Allocated in 0.0414 seconds
Start processing input "test2.txt"
File "test2.txt" is not in sorted order at line 802
Line 801: 0x030x030x030x030x030x03
Line 802: 0x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x030x03
Total runtime 0.0530 second
```
